name: GitHub Repo View Tracker

on:
  schedule:
    - cron: '0 0 */14 * *'  # Every 14 days at midnight UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  run-tracker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Use the latest Python 3 version

      - name: Install Dependencies
        run: pip install PyGithub

      - name: Run the Tracker Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Securely use GitHub token
        run: python repo_view_tracker.py

      - name: Commit Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add repo_views.json
          git commit -m "Update repo view statistics (Automated)"
          git push
